.TH "math" 3 "Version 000" "Matrix" \" -*- nroff -*-
.ad l
.nh
.SH NAME
math
.SH SYNOPSIS
.br
.PP
.SS "Классы"

.in +1c
.ti -1c
.RI "class \fBMatrix\fP"
.br
.in -1c
.SS "Определения типов"

.in +1c
.ti -1c
.RI "typedef double \fBreal\fP"
.br
.in -1c
.SH "Типы"
.PP 
.SS "typedef double \fBmath::real\fP"

.SH "Автор"
.PP 
Автоматически создано Doxygen для Matrix из исходного текста\&.
