.TH "src/matrix.h" 3 "Version 000" "Matrix" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/matrix.h
.SH SYNOPSIS
.br
.PP
\fR#include <vector>\fP
.br

.SS "Классы"

.in +1c
.ti -1c
.RI "class \fBmath::Matrix\fP"
.br
.in -1c
.SS "Пространства имен"

.in +1c
.ti -1c
.RI "namespace \fBmath\fP"
.br
.in -1c
.SS "Определения типов"

.in +1c
.ti -1c
.RI "typedef double \fBmath::real\fP"
.br
.in -1c
.SH "Автор"
.PP 
Автоматически создано Doxygen для Matrix из исходного текста\&.
